# [[language]]
# name = "rust"
# language-server = { command = "ra-multiplex" } 

#[language.config]
#cargo = { features = ["db-tests"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
